const ANTD = require('./antd.config')
const ADMIN = require('./admin.config')
const ANIMATE = require('./animate.config')
const setting = require('./setting.config')

/**
 * 所有的setting集合
 * @type {{ANTD: {theme: {light: {"menu-dark-highlight-color": string, "body-background": string, "shadow-color": string, "text-color-secondary": string, "background-color-light": string, "text-color-inverse": string, "checkbox-check-color": string, "border-color-split": string, "menu-dark-arrow-color": string, "table-selected-row-bg": string, "heading-color": string, "layout-body-background": string, "menu-dark-color": string, "table-expanded-row-bg": string, "disabled-color": string, "text-color": string, "btn-primary-color": string, "component-background": string, "background-color-base": string}, night: {"menu-dark-highlight-color": string, "body-background": string, "shadow-color": string, "text-color-secondary": string, "background-color-light": string, "text-color-inverse": string, "checkbox-check-color": string, "border-color-split": string, "menu-dark-arrow-color": string, "table-selected-row-bg": string, "heading-color": string, "layout-body-background": string, "menu-dark-color": string, "table-expanded-row-bg": string, "disabled-color": string, "text-color": string, "btn-primary-color": string, "component-background": string, "background-color-base": string}, dark: {"menu-dark-highlight-color": string, "body-background": string, "shadow-color": string, "text-color-secondary": string, "background-color-light": string, "text-color-inverse": string, "checkbox-check-color": string, "border-color-split": string, "menu-dark-arrow-color": string, "table-selected-row-bg": string, "heading-color": string, "layout-body-background": string, "menu-dark-color": string, "table-expanded-row-bg": string, "disabled-color": string, "text-color": string, "btn-primary-color": string, "component-background": string, "background-color-base": string}}, primary: {color: string, light: {menuColors: string[]}, success: string, night: {menuColors: string[]}, dark: {menuColors: string[]}, warning: string, error: string}}, ANIMATE: {preset}, ADMIN: {layout: {SIDE: string, HEAD: string}, animates: *, palettes, theme: {mode: {NIGHT: string, LIGHT: string, DARK: string}}}, setting: *|{}}}
 */
module.exports = {ANTD, ADMIN, ANIMATE, setting}
